export const obj = [
    {
        key: 'Q',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'W',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'E',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'R',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'T',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'Y',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'U',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'I',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'O',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'P',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'A',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'S',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'D',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'F',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'G',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'H',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'J',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'K',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'L',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'Z',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'X',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'C',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'V',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'B',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'N',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
    {
        key: 'M',
        clicked: false,
        rightplace: false,
        wrongplace: false,
        wrongletter: false,
    },
];
