export const obj = [
    {
        active: true,
        input: [
            {
                active: true,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
        ],
    },
    {
        active: false,
        input: [
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
        ],
    },
    {
        active: false,
        input: [
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
        ],
    },
    {
        active: false,
        input: [
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
        ],
    },
    {
        active: false,
        input: [
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
        ],
    },
    {
        active: false,
        input: [
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
            {
                active: false,
                clicked: false,
                rightplace: false,
                wrongplace: false,
                wrongletter: false,
                value: '',
            },
        ],
    },
];
